name: Build & Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_NON_PROD }}
  IMAGE_NAME: deepdb
  REGION: us-east1
  CLUSTER_NAME: mantisanalytics-cluster
  CLUSTER_ZONE: us-east1
  DEPLOYMENT_NAME: sa-service-deployment
  NAMESPACE: default

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY_NON_PROD }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Set image tag
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-5)
          echo "TAG=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --push .

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials \
            ${{ env.CLUSTER_NAME }} \
            --region ${{ env.REGION }}

      - name: Update Deployment image
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.IMAGE_NAME }}=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            -n ${{ env.NAMESPACE }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
